server {
  listen 8080;
  root /usr/share/nginx/html;
  absolute_redirect off;

  location /metra/assets/ {
    expires max;
    add_header Cache-Control "public, immutable";
  }

  location /metra/ {
    add_header Cache-Control "no-cache";
    try_files $uri $uri/ /metra/index.html;
  }
}
